version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql/:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - '3001:3001'
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile-prod
    ports:
      - '3000:80'
  reverse_proxy:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=siggame.io
      - SUBDOMAINS=mmai,mmai-server,
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=token #optional
      - EMAIL=siggame@umsystem.edu #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=true #optional
      # - EXTRA_DOMAINS=extradomains #optional
      - STAGING=false #optional
    volumes:
      - ./.docker/letsencrypt:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
